---
app_name: gnomekiosk-demo-shell

extension_uuid: kiosk-layout-helper@gnomekiosk.demo
extension_dir_local: "{{ playbook_dir }}/../gnome-shell-extension/{{ extension_uuid }}"

deploy_target: shell

kiosk_verify_scope: auto
